### ISSUE TITLE
Cannot view Netflix due to unimplemented CreateFileIO

### ISSUE THREAD

**Issue by daemonblade** [shkhln/foreign-cdm#3]
I'm running chromium + foreign-cdm on FreeBSD. When I attempt to view Netflix, it fails with the following errors on stdout:

lib.cpp:80: info: CreateSessionAndGenerateRequest; promise_id = 3; session_type = 0; init_data_type = 0; init_data = 1bb11863200; init_data_size = 52
worker.cpp:240: info: createSessionAndGenerateRequest
*** Fatal uncaught kj::Exception: worker.cpp:546: unimplemented: CreateFileIO
*** Fatal uncaught kj::Exception: capnp/rpc.c++:2778: disconnected: Peer disconnected.
stack: 1bb18037f18 1bb1802c580 1bb1816a310
[34603:-692588544:1004/072526.678703:ERROR:mojo_cdm.cc(118)] Remote CDM connection error: custom_reason=0, description=""

**Comment by shkhln** [comment]
To be clear, that part wasn't implemented because it's not used by a [few](https://reference.dashif.org/dash.js/latest/samples/drm/widevine.html) [public](https://bitmovin.com/demos/drm) [demos](https://demo.castlabs.com/) I could find. Same goes for all other stubbed parts. I'll get to it within a week.

**Comment by shkhln** [comment]
Does 4a4990d92731a05b2395cb17cad21d9f684e5355 help? (Edit the hash in the port's makefile and regenerate checksum with `make makesum`, then build it.)

**Comment by juikim** [comment]
> Does [4a4990d](https://github.com/shkhln/foreign-cdm/commit/4a4990d92731a05b2395cb17cad21d9f684e5355) help? (Edit the hash in the port's makefile and regenerate checksum with `make makesum`, then build it.)

Netflix works after this change!  `GetStatusForPolicy` for Amazon Prime Video and Disney+, please.  ;-)

**Comment by shkhln** [comment]
> `GetStatusForPolicy` for Amazon Prime Video and Disney+, please. ;-)

71711f1876fc966ef6712e6ee91ecc25a1bda0ce

**Comment by daemonblade** [comment]
I can confirm that Netflix works with the latest commit!
Woohoo!

**Comment by juikim** [comment]
> > `GetStatusForPolicy` for Amazon Prime Video and Disney+, please. ;-)
> 
> [71711f1](https://github.com/shkhln/foreign-cdm/commit/71711f1876fc966ef6712e6ee91ecc25a1bda0ce)

Good news is Hulu works now!  Bad news is Amazon Prime Video and Disney+ now request `OnResolveKeyStatusPromise`.

**Comment by shkhln** [comment]
> `OnResolveKeyStatusPromise`

e953bc0d35344b7e4474969ed37f4e0f9be01451

**Comment by juikim** [comment]
> > `OnResolveKeyStatusPromise`
> 
> [e953bc0](https://github.com/shkhln/foreign-cdm/commit/e953bc0d35344b7e4474969ed37f4e0f9be01451)

Both Amazon Prime Video and Disney+ work fine now, thanks!

**Comment by shkhln** [comment]
Do you have a Spotify subscription by chance? That should exercise `initializeAudioDecoder` I believe.

**Comment by juikim** [comment]
> Do you have a Spotify subscription by chance? That should exercise `initializeAudioDecoder` I believe.

Yes, I do and it worked fine, too!

**Comment by shkhln** [comment]
Oh well, we'll leave it stubbed then.
