### ISSUE TITLE
make: exec(./build/capnp-fbsd/c++/src/capnp/capnp) failed (No such file or directory)

### ISSUE THREAD

**Issue by Marietto2008** [shkhln/foreign-cdm#5]
Hello.

I have added : linux_enable="yes" to /etc/rc.conf,but I get the same error when I try to compile the foreign-cdm port (it works if I do the installation of the package) :

[mario@marietto /usr/ports/www/foreign-cdm]==> make clean
[mario@marietto /usr/ports/www/foreign-cdm]==> make MAKE_JOBS_UNSAFE=yes

===>  Building for foreign-cdm-20231217_3
./build/capnp-fbsd/c++/src/capnp/capnp compile -obuild/capnp-fbsd/c++/src/capnp/capnpc-c++ src/cdm.capnp
make: exec(./build/capnp-fbsd/c++/src/capnp/capnp) failed (No such file or directory)
*** Error code 1

Stop.
make: stopped in /usr/ports/www/foreign-cdm/work/foreign-cdm-3fe4d7130bb1e0581b5310635515a120f2794b88
*** Error code 1

NB : I have updated several times the ports tree.
Stop.
make: stopped in /usr/ports/www/foreign-cdm

**Comment by shkhln** [comment]
The output is consistent with linux64.ko not being loaded. Now, I hope never see any notifications from you specifically.
